 # Table of Contents
<div class="toc" style="margin-top: 1em;"><ul class="toc-item" id="toc-level0"></ul></div>

In [36]:
# 连接吴浩池数据库
import psycopg2 as data
# help(data)
conn=data.connect(database='mdserver',user='mdapi',password='mdapi',host='192.168.1.190',port='5432')


In [37]:
query="""
select distinct ticker from idxbars 
where
datetime>='2017-03-06'
and
datetime<='2017-03-07'
and
ticker like '%399005'



"""
cur=conn.cursor()
cur.execute(query)
result=cur.fetchall()

In [19]:

#print(result[0])
r=[]
for v in result[0]:
    r.append(v)
    
print(v)

2016-01-29 06:26:08.503000+08:00


In [39]:
print(result[0])

('SZ399005',)


In [41]:
import pandas as pd
s=pd.DataFrame()

In [42]:
s.columns

Index([], dtype='object')

In [1]:
help(pd.concat)

NameError: name 'pd' is not defined

In [9]:
import pandas as pd
import numpy as np
s=pd.DataFrame(np.random.randn(10, 5),columns=['a', 'b', 'c', 'd', 'e'])
s.head(5)

a         b         c         d         e
0 -0.122630 -2.534444 -1.478167  0.113474 -0.804780
1 -1.065302  0.668490  2.306082 -2.304199 -0.829327
2 -1.092687 -1.510536  0.133511  1.222593 -1.749078
3  0.151790  0.139944  1.654250 -0.001076  1.221751
4  1.760669  0.347945 -0.326471 -0.536526  0.362750

In [12]:
s['f']=np.nan


a         b         c         d         e   f
0 -0.122630 -2.534444 -1.478167  0.113474 -0.804780 NaN
1 -1.065302  0.668490  2.306082 -2.304199 -0.829327 NaN
2 -1.092687 -1.510536  0.133511  1.222593 -1.749078 NaN
3  0.151790  0.139944  1.654250 -0.001076  1.221751 NaN
4  1.760669  0.347945 -0.326471 -0.536526  0.362750 NaN
5  0.197461 -0.796635 -1.775054  1.725509  0.122831 NaN
6  0.574983  1.268381  0.406346 -0.492788 -1.684972 NaN
7  0.289297  0.566592  1.510069 -0.796655  1.714690 NaN
8 -0.318326 -2.792314  1.568367  1.272420 -1.407933 NaN
9 -0.766308 -0.031515 -0.838003 -1.325103 -1.046758 NaN

In [15]:
a=['a', 'b', 'c', 'd', 'e']

In [17]:
b=set(a)

In [19]:
c=list(b)


In [22]:
c


['d', 'b', 'e', 'c', 'a']

In [27]:
b=s['a'].values

In [35]:
#help(np.vstack)
list(set(np.hstack((b,b))))


[-0.12263046526150706,
 1.7606687577948645,
 0.15178996637058126,
 0.19746053101726968,
 0.57498295374812392,
 0.28929691734294749,
 -0.31832612396068066,
 -0.76630813326591818,
 -1.0653021318341924,
 -1.0926866123062073]

In [43]:
b=np.ones([4,2])*np.nan
print(b)

[[ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]]


In [51]:
a=np.array([2,3,1,5,7])
b=np.nonzero(a>1)[0][:]
print(b)

[0 1 3 4]


In [57]:
b=np.empty([3,2])
print(b)
b[0]

[[  6.95219434e-310   6.95219434e-310]
 [  6.95219434e-310   6.95219434e-310]
 [  6.95219434e-310   6.95219434e-310]]


array([  6.95219434e-310,   6.95219434e-310])

In [59]:
len(np.array([]))

0

In [67]:
a=np.array([1,0])

In [69]:
a.astype('bool')


array([ True, False], dtype=bool)

In [1]:
import xgboost as xgb

In [ ]:
xgb.